server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@hackathon.n5sib2v.mongodb.net/hackathon?retryWrites=true&w=majority&appName=Hackathon
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
  swagger-ui:
    enabled: true

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: http://localhost:${server.port}
    title: Chat App APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

JWT_SECRET_KEY : ${KEY}