server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:hackathon_db}?currentSchema=public&createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:devpostgre}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
  swagger-ui:
    enabled: true

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: http://localhost:${server.port}
    title: Chat App APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

JWT_SECRET_KEY : ${KEY}