server:
  port: 8090

spring:
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@hackathon.n5sib2v.mongodb.net/hackathon?retryWrites=true&w=majority&appName=Hackathon
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB        # Kích thước tối đa cho 1 file
      max-request-size: 500MB     # Tổng kích thước request
      file-size-threshold: 5MB    # Ngưỡng lưu file tạm

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
  swagger-ui:
    enabled: true

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: http://localhost:${server.port}
    title: Chat App APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

JWT_SECRET_KEY : ${KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}